### ISSUE TITLE
Unable to create DHCP Listener socket!

### ISSUE THREAD

**Issue by gmcbrien** [SynAckFin/TuyOTA#20]
Device is a Teckin SP22. I ran the script via SSH. Session hung, so I ran it again locally and receive the following error. 

The 192.168.1.12 address is the address of the plug, and can be pinged.

pi@raspberrypi:~/TuyOTA $ sudo ./tuyota.pl -ip 192.168.1.12 -s my_ssid -p my_ssid_password
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1395
Unable to create DHCP Listener socket! Address already in use at ./tuyota.pl line 188.
Exiting....
Shutting down...

Any advice how to get further?

Happy to provide any further details, thanks!

**Comment by SynAckFin** [comment]
It looks like your pi is running a DHCP server. You need to stop the DHCP server before running the script.

**Comment by gmcbrien** [comment]
So I killed the DHCP server, still no luck. The IP Address that it's complaining about is actually assigned to my WLAN0 interface.
As root, I kill the wpa_supplicant process (otherwise the AP won't appear), I kill the DHCP Process, I run the start_flash.sh, I can connect my mobile to the vtrust-flash AP, I have the light flashing on the Teckin SP22 plug, I press enter and then just ............. (nothing)
I am not sure if the SP22 is actually even supported, so I may be wasting my time...?

**Comment by gmcbrien** [comment]
Thanks for the response. I stopped the DHCP Server, but still no succes. I agree that I'm getting further though. The screenlog.0 file shows the following. It now just sits there producing dots....

Basically, as root, I kill wpa_supplicant process (otherwise AP won't appear), I kill the DHCP Server, the WLAN0 gets the IP 10.42.42.1, I run the start_flash.sh, I can connect my mobile to the vtrust-flash AP, accept yes, press butt on on plug, make blue light flash, press enter.

```bash
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
Starting DNSMASQ server...
RTNETLINK answers: File exists
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:XX:XX:XX and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: associated
wlan0: AP-STA-CONNECTED dc:4f:22:XX:XX:XX
wlan0: STA dc:4f:22:XX:XX:XX RADIUS: starting accounting session 5C91467D-00000000
wlan0: STA dc:4f:22:XX:XX:XX WPA: pairwise key handshake completed (RSN)
1553024637: mosquitto version 1.3.4 (build date 2018-09-28 22:21:32+0000) starting
1553024637: Using default config.
1553024637: Opening ipv4 listen socket on port 1883.
1553024637: Opening ipv6 listen socket on port 1883.
wlan0: STA 6c:c7:ec:XX:XX:XX IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 6c:c7:ec:XX:XX:XX
wlan0: STA 6c:c7:ec:XX:XX:XX RADIUS: starting accounting session 5C91467D-00000001
wlan0: STA 6c:c7:ec:XX:XX:XX WPA: pairwise key handshake completed (RSN)
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED dc:4f:22:XX:XX:XX
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: disassociated
Put Device in Learn Mode!, sending Smartlink Packets now
Smartlink in progress
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
Sending Packets and wait 60 seconds.
wlan0: STA dc:4f:22:XX:XX:XX IEEE 802.11: associated
wlan0: AP-STA-CONNECTED dc:4f:22:XX:XX:XX
wlan0: STA dc:4f:22:XX:XX:XX RADIUS: starting accounting session 5C91467D-00000002
wlan0: STA dc:4f:22:XX:XX:XX WPA: pairwise key handshake completed (RSN)
```

**Comment by gmcbrien** [comment]
BTW, I also see an error in the screenlog just before the output above

```bash
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1655
    async def _execute(
            ^
SyntaxError: invalid syntax
Backing up NetworkManager.cfg...
Restarting NetworkManager...
```

**Comment by gmcbrien** [comment]
I killed DHCP - no luck I'm afraid :( The IP is actually assigned to my WLAN0 interface.

```bash
root@raspberrypi:/home/pi/TuyOTA# ps -ef | grep dhcp
root       497     1  0 21:00 ?        00:00:00 /sbin/dhcpcd -q -b
root      1954  1823  0 21:05 pts/0    00:00:00 grep dhcp

root@raspberrypi:/home/pi/TuyOTA# kill 497

root@raspberrypi:/home/pi/TuyOTA# ./tuyota.pl 
Getting interface into stable state
RTNETLINK answers: Cannot assign requested address
Done
Using WiFi device wlan0 for Access Point
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 1970
Unable to create DHCP Listener socket! Address already in use at ./tuyota.pl line 188.
Exiting....
Shutting down...
root@raspberrypi:/home/pi/TuyOTA# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.41/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8dd6:f30a:xxxx:xxxx/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:XX:XX:XX brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.143/24 brd 192.168.1.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet 10.44.57.1/24 scope global wlan0
       valid_lft forever preferred_lft forever
root@raspberrypi:/home/pi/TuyOTA# 
```

**Comment by SynAckFin** [comment]
dhcpcd is the client daemon not the server. You have something listening on port 67.
Try the following:
`# lsof -nP | grep UDP.*:67
`
It should show you what process is listening to that port.
It also looks like your wlan0 has an IP address which means there is something managing it. The script is unlikely to work if there are other processes managing the WiFi device.

**Comment by Geoff571** [comment]
It looks like I've got the same issue, though I can't see anything else controlling wlan0. 

```
Starting Access Point with SSID ZAGDU-789
Giving Access Point IP address 10.44.57.1, pid is 747
Unable to create DHCP Listener socket! Address already in use at ./tuyota.pl line 188.
Exiting....
Shutting down...
**pi@raspberrypi:~/TuyOTA $ lsof -nP | grep UDP.*:67**
pi@raspberrypi:~/TuyOTA $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:77:28:48 brd ff:ff:ff:ff:ff:ff
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:b0:8c:05:16:e1 brd ff:ff:ff:ff:ff:ff
    inet 10.44.57.1/24 scope global wlan0
       valid_lft forever preferred_lft forever
pi@raspberrypi:~/TuyOTA $ 

```
Did anyone manage to work out what's going on?

**Comment by SynAckFin** [comment]
Have you tried running:
`# lsof -nP | grep UDP.*:67 `

**Comment by Geoff571** [comment]
Yes, there was nothing output from the command, it's in the code pasted above

**Comment by SynAckFin** [comment]
The lsof command should be run as root (sudo).

The error "Address already in use" usually means there is something else bound to the port and lsof should find the process.
Alternatively you could try:
`sudo netstat -anlp
`
and look for an output line like this:
`udp        0      0 0.0.0.0:67    ....
`
You could also try editing tuyota.pl and uncomment line 190 so it looks like this:
`      LocalAddr => $WiFiIPAddr,
`

**Comment by Geoff571** [comment]
I never got to the bottom of the issue, but I did manage to get the devices flashed using the Tuya-convert script. When I get a bit more time, I'll try to have another look at why I couldn't get this script working.

Thanks for all your help

**Comment by Geoff571** [comment]
Ok, I ran the lsof command as root and it looks like dnsmasq is on port 67. So that at least indicates why the script was failing
